# Copyright 2015 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

install:
# TODO: Investigate installing with chocolatey or scoop.
  - ps: wget https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/dartsdk-windows-x64-release.zip -OutFile dart-sdk.zip
  - cmd: echo "Unzipping dart-sdk..."
  - cmd: 7z x dart-sdk.zip -o"C:\tools" -y > nul
  - set PATH=%PATH%;C:\tools\dart-sdk\bin
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
  - pub get

build: off

test_script:
  - pub global activate tuneup
  - pub global run tuneup check
  - dart --checked test\all.dart
