name: sky_tools
version: 0.0.18
description: Tools for building Flutter applications
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  archive: ^1.0.20
  args: ^0.13.0
  mustache4dart: ^1.0.0
  path: ^1.3.0
  shelf_route: ^0.13.4
  shelf_static: ^0.2.3
  shelf: ^0.6.2
  test: ">=0.12.4+5 <0.12.5"
  yaml: ^2.1.3

dev_dependencies:
  flutter: any
  mockito: ^0.10.1

# Add the bin/sky_tools.dart script to the scripts pub installs.
executables:
  sky_tools:
