name: sky_tools
version: 0.0.30
description: Tools for building Flutter applications
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: '>=1.13.0-dev.7.4 <2.0.0'

dependencies:
  archive: ^1.0.20
  args: ^0.13.0
  asn1lib: ^0.4.1
  cipher: ^0.7.1
  flx: 0.0.1
  crypto: ^0.9.1
  mustache4dart: ^1.0.0
  path: ^1.3.0
  shelf_route: ^0.13.4
  shelf_static: ^0.2.3
  shelf: ^0.6.2
  test: ^0.12.5
  yaml: ^2.1.3

dev_dependencies:
  mockito: "^0.10.1"

# Add the bin/sky_tools.dart script to the scripts pub installs.
executables:
  sky_tools:
